stages:
  data_cleaning:
    cmd: python scripts/data_cleaning.py
    deps:
    - data/spotify_songs.csv
    - scripts/data_cleaning.py
    outs:
    - data/spotify_cleaned.csv
  feature_engineering:
    cmd: python scripts/feature_engineering.py
    deps:
    - data/spotify_cleaned.csv
    - scripts/feature_engineering.py
    outs:
    - data/spotify_featured.csv
